import allure
from lib.main_page import MainPage
from lib.sign_in_page import SignInPage
from lib.create_page import CreatePage
from lib.profile_page import ProfilePage

@allure.story("Выполнение регистрации аккаунта")
def test_create_registration(browser):
    link = "http://automationpractice.com/index.php"
    page = MainPage(browser,link)
    page.open()
    page.should_be_button_sign_in()
    page.go_to_sign_in()
    sign_in_page = SignInPage(browser, browser.current_url)
    sign_in_page.should_be_sign_in_url()
    sign_in_page.should_be_input_mail_registration()
    sign_in_page.input_mail_registration()
    sign_in_page.should_be_button_create()
    sign_in_page.go_to_create()
    create_page = CreatePage(browser, browser.current_url)
    create_page.should_be_create_url()
    create_page.should_be_radiobutton_gender()
    create_page.radiobutton_gender()
    create_page.should_be_input_first_name()
    create_page.input_first_name()
    create_page.should_be_input_last_name()
    create_page.input_last_name()
    create_page.should_be_input_mail()
    create_page.input_mail()
    create_page.should_be_input_password()
    create_page.input_password()
    create_page.should_be_select_days()
    create_page.select_days()
    create_page.should_be_select_month()
    create_page.select_month()
    create_page.should_be_select_year()
    create_page.select_year()
    create_page.should_be_checkbutton_sign()
    create_page.checkbutton_sign()
    create_page.should_be_checkbutton_receive()
    create_page.checkbutton_receive()
    create_page.should_be_input_firstname()
    create_page.input_firstname()
    create_page.should_be_input_lastname()
    create_page.input_lastname()
    create_page.should_be_input_company()
    create_page.input_company()
    create_page.should_be_input_address()
    create_page.input_address()
    create_page.should_be_input_address_dop()
    create_page.input_address_dop()
    create_page.should_be_input_city()
    create_page.input_address_city()
    create_page.should_be_select_state()
    create_page.select_state()
    create_page.should_be_input_index()
    create_page.input_address_index()
    create_page.should_be_textarea()
    create_page.textarea_input()
    create_page.should_be_input_home_telefon()
    create_page.input_home_telefon()
    create_page.should_be_input_mobile_telefon()
    create_page.input_mobile_telefon()
    create_page.should_be_input_name_on_site()
    create_page.input_name_on_site()
    create_page.should_be_button_register()
    create_page.button_register()
    account_page = ProfilePage(browser, browser.current_url)
    account_page.should_be_account()


